### ISSUE TITLE
Identify Existing Features in Project Repository

### ISSUE THREAD

**Issue by Kanchanop6509650229** [Kanchanop6509650229/CS360-QWERTYUIOP#6]
**วัตถุประสงค์**:
- ค้นหาและทำความเข้าใจกับ features ที่มีอยู่ในต้นฉบับโปรเจกต์บน GitHub เพื่อให้มั่นใจว่าทุกความต้องการฟีเจอร์ต่างๆ ถูกรวมและเอกสารไว้อย่างถูกต้อง

**Task**:
- [x] **ตรวจสอบ Codebase**: ทำการสำรวจและตรวจสอบ codebase เพื่อระบุ features หลักและรองที่มีอยู่ในโปรเจกต์
- [x] **ทบทวนเอกสาร**: ตรวจสอบเอกสารที่เกี่ยวข้องกับโปรเจกต์ เช่น README, Wiki, หรือใน comments ของโค้ด เพื่อหาข้อมูลเกี่ยวกับ features ที่ระบุไว้
- [x] **จัดทำรายงาน Features**: สรุป features ที่พบและทำความเข้าใจในรายงานเพื่อให้ทีมทราบถึงสถานะปัจจุบันและแนวทางการพัฒนาต่อไป
- [x] **ประเมินความครบถ้วน**: ประเมินว่า features ที่มีอยู่ครอบคลุมความต้องการของโปรเจกต์ในปัจจุบันหรือต้องการการปรับปรุงเพิ่มเติม

**Comment by waradis6509650088** [comment]
Main Features 
--- 
**ฟีเจอร์หลัก**: ค้นหามื้ออาหารจากชนิดของอาหารและตำแหน่งปัจจุบันที่ได้จากผู้ใช้ โดยการแสดง Blog post ตามข้อมูลที่ผู้ใช้ให้
**ฟีเจอร์เพิ่มเติม**: มี subscription ที่สามารถซื้อได้ 

Technical Features 
--- 
**Backend**: Strapi API 
**Frontend**: Nextjs + Tailwind

**Comment by Kanchanop6509650229** [comment]
ตรง Feature 2: the application shows relevant blog post according to the user's search terms เหมือนว่าในเว็ปจะมีแค่ให้เลือกหมวดนะ แบบนี้นับไหม 5555 ![Image](https://github.com/user-attachments/assets/bb731b1e-86ac-4fb8-b6e4-d93c05231b8a)

**Comment by waradis6509650088** [comment]
> ตรง Feature 2: the application shows relevant blog post according to the user's search terms เหมือนว่าในเว็ปจะมีแค่ให้เลือกหมวดนะ หาช่อง search ไม่เจอ แบบนี้นับไหม 5555 ![Image](https://github.com/user-attachments/assets/bb731b1e-86ac-4fb8-b6e4-d93c05231b8a)

แก้เป็น user's chosen food categories แทนนะ

**Comment by Kanchanop6509650229** [comment]
ใช่ๆ ถ้าแก้แล้วอัพลง readme ได้เลยๆ นอกนั้นโอเคละๆ
